@startuml
skinparam monochrome reverse
skinparam actorStyle hollow

title ReservationEntity Lifecycle
ReservationRequest --> (INIT)
(INIT) --> (COLLECTING): ResourceSelected
(SELECTING) --> (SELECTING): ResourceSelected
(COLLECTING) --> (SELECTING): ResourceSelected
(UNAVAILABLE) <-- (SELECTING): expire
(UNAVAILABLE) <-- (COLLECTING): expire
(UNAVAILABLE) <-- (INIT): expire
(FULFILLED) <-- (SELECTING): fulfill
(UNAVAILABLE) <-up- (SELECTING): Rejected
(FULFILLED) --> (CANCEL_REQUESTED): cancelRequest
(CANCEL_REQUESTED) --> (CANCELLED): cancel
'COMPLETE is when a reservation is in the past
(FULFILLED) --> (COMPLETE): complete
@enduml