@startuml
skinparam actorStyle hollow

title Dependencies
(viewmodel) --> (dto)
(viewmodel) --> (domain)
(view) --> (entities)
(view) --> (viewmodel)
(actions) --> (entities)
(actions) --> (events)
(actions) --> (dto)
(entities) --> (events)
(entities) --> (dto)
(events) --> (dto)
(dto) --> (domain)
@enduml