@startuml
skinparam monochrome reverse
skinparam actorStyle hollow

title ReservationEntity Lifecycle
RunSearch -up-> (INIT): emptyState()
(INIT) --> (SELECTING): ResourceSelected
(SELECTING) --> (SELECTING): ResourceSelected
(DONE) <-down- (INIT): Rejected
(DONE) <-- (SELECTING): Booked
(UNAVAILABLE) <-up- (SELECTING): Rejected
@enduml