@startuml
skinparam monochrome reverse
skinparam actorStyle hollow

title ReservationEntity Lifecycle
Request -> (INIT)
(INIT) --> (COLLECTING): Initiated
(COLLECTING) -> (COLLECTING): (no)
(COLLECTING) --> (SELECTING): (yes)
(SELECTING) --> (SELECTING): (yes/no)
(UNAVAILABLE) <-left- (COLLECTING): Rejected
(FULFILLED) <-- (SELECTING): Accepted
(SELECTING) -> (COLLECTING): Rejected
(FULFILLED) --> (CANCELLED)
@enduml