@startuml
skinparam monochrome reverse
skinparam actorStyle hollow

title ReservationEntity Lifecycle
RunSearch -up-> (INIT): emptyState()
(INIT) --> (SELECTING): ResourceSelected
(SELECTING) --> (SELECTING): ResourceSelected
(UNAVAILABLE) <-down- (INIT): Rejected
(FULFILLED) <-- (SELECTING): Booked
(UNAVAILABLE) <-up- (SELECTING): Rejected
(FULFILLED) --> (CANCELLED): Canceled
(FULFILLED) <-- (CANCELLED): Rebooked
(COMPLETE) <-- (CANCELLED): Timeout
(FULFILLED) --> (COMPLETE): Timeout
@enduml